arb-dir: lib/core/l10n/arb
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
untranslated-messages-file: lib/core/l10n/untranslated.txt
output-dir: lib/core/l10n/gen
nullable-getter: false
