import 'package:drift/drift.dart';

/// Every activation code ever generated by the Developer, and its
/// redemption state. `code` is the full signed `UNPS-...-...` string; it is
/// also the natural unique key.
class ActivationCodes extends Table {
  TextColumn get id => text()();
  TextColumn get code => text().unique()();
  TextColumn get storeNameRef => text()();
  TextColumn get tier => text()(); // LicenseTier.name
  DateTimeColumn get issuedAt => dateTime()();
  DateTimeColumn get expiresAt => dateTime().nullable()(); // null = lifetime
  TextColumn get status => text().withDefault(const Constant('unused'))(); // unused/active/expired/revoked
  TextColumn get redeemedByStoreId => text().nullable()();
  DateTimeColumn get redeemedAt => dateTime().nullable()();

  @override
  Set<Column> get primaryKey => {id};
}
